name: test_flutter
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  gif: ^2.3.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  anim_search_bar: ^2.0.3
  animated_search_bar: ^2.7.2
  searchbar_animation: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/gif/
    - assets/image/